#Date: 13th of Jun, 2025
#Location: Blacksburg, VA (USA)
#Purpose: Create a frequency table for strains based on CDHit Clusters
#Input: CDHit Cluster files, list of sample names
#output: N strain fasta files


import os
import argparse
import sys
import traceback
import time


parser = argparse.ArgumentParser()

parser.add_argument("-c","--clusters", required=True, help="CDHit Strain clusters")
parser.add_argument("-m","--matrix", required=True, help="MetaStrainer Abundance file generated by GenerateStrainAbundanceMatrix.py")
parser.add_argument("-o","--outputfile",default="SampleX_Statistics_",help="Name of output statistics")

args = parser.parse_args()



#def parse_cdhit_clstr(clstr_file):
strainClusterMap = {}
repStrain = None
currentCluster = ""
clusterIndex = -1 #I need to keep cluster numbering similar to CDHitcluster file
with open(args.clusters, 'r') as cdhit_cluster_file:
	for line in cdhit_cluster_file:
		line = line.strip()
		if line.startswith('>Cluster'):
			repStrain = None
			clusterIndex = clusterIndex + 1
		else:
			lineContents = line.split('>')
			if len(lineContents) < 2:
				continue
			strainID = lineContents[1].split('...')[0]
			
			# >Cluster 0
			# 0       1621979nt, >D14_L1_1_S1_L001_ConcatStrain1... *
			# 1       1621979nt, >D14_L1_2_S19_L001_ConcatStrain1... at +/99.71%
			# 2       1621979nt, >D14_L1_4_S17_L001_ConcatStrain1... at +/99.64%
			if '*' in line:
				repStrain = "Cluster" +str(clusterIndex) + "_" + strainID
			
			strainClusterMap[strainID] = repStrain


with open(args.matrix, 'r') as abundances_matrix_file:
	#Have to load matrix at once
	lines = abundances_matrix_file.readlines()

#header = lines[0].strip().split('\t')
header = lines[0].rstrip('\n').split('\t')

#header[0] is empty or will say strain/sample, I haven't finished that yet
samples = header[1:]

strainAbundanceMatrix = {}
for line in lines[1:]:
	lineContents = line.strip().split('\t')
	strain = lineContents[0]
	values = list(map(float, lineContents[1:]))
	strainAbundanceMatrix[strain] = values

clusterMatrix = {}

for strain, abundances in strainAbundanceMatrix.items():
	cluster = strainClusterMap.get(strain)
	if cluster is None:
		continue  # skip strains not found in strainClusterMap
	if cluster not in clusterMatrix:
		clusterMatrix[cluster] = [0.0] * len(abundances)
	for i in range(len(abundances)):
		clusterMatrix[cluster][i] += abundances[i]


with open(args.outputfile, 'w') as write_clusters:
	write_clusters.write('ClusterID\t' + '\t'.join(samples) + '\n')
	for cluster in sorted(clusterMatrix.keys()):
		values = '\t'.join(f'{v:.2f}' for v in clusterMatrix[cluster])
		write_clusters.write(f'{cluster}\t{values}\n')
